node.js:
  image: node:latest
  cache:
    paths:
      - node_modules
  script:
    # Workaround for https://github.com/docker/hub-feedback/issues/727
    - apt-get update
    - apt-get install -y --no-install-recommends bsdtar
    - tar --version # before
    - ln -sf `which bsdtar` `which tar` # 🖕 tar
    - tar --version # after
    - bsdtar --version

    # Install Meteor
    - curl https://install.meteor.com/ | bash

    # Install dependencies and run tests
    - export NPM_CONFIG_LOGLEVEL="warn"
    - export METEOR_ALLOW_SUPERUSER="true"
    - npm it
