# Variables needed for this script are:

# Case 1: Stored on Travis Settings
  # For all environments:
    # - DOCKER_CI_REPO_NAME
    # - DOCKER_USERNAME
    # - DOCKER_PASSWORD

  #For dev environment:
    # - AWS_ACCOUNT_USER_ID_DEV
    # - AWS_ACCOUNT_SECRET_DEV
    # - AWS_PROFILE_DEV <-- is this needed?

  #For Prod environment:
    # - AWS_ACCOUNT_USER_ID_PROD
    # - AWS_ACCOUNT_SECRET_PROD
    # - AWS_PROFILE_PROD <-- is this needed?

  #For Demo environment:
    # - AWS_ACCOUNT_USER_ID_DEMO
    # - AWS_ACCOUNT_SECRET_DEMO
    # - AWS_PROFILE_DEMO <-- is this needed?

# Case 2: Created when Travis CI runs
    # - IMAGE_TAG

# language: node_js
# node_js:
#   - lts/*
language: generic
services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    #Add IMAGE_TAG variable to build docker image
    - IMAGE_TAG=${TRAVIS_COMMIT::7}

before_install:
  # Removed command as pyenv is no longer found during deploy
  #- pyenv global 2.7.14  # For removing SNIMissingWarning warnings
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -o $HOME/.local/bin/ecs-cli
    https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest &&
    chmod +x $HOME/.local/bin/ecs-cli

# cache:
#   directories:
#     - node_modules

install:
  # build the docker image that will deploy the code
  - docker build -t $DOCKER_CI_REPO_NAME . 

# script:
#   - npm t

# Adding script deploy docker image to docker repository
# after_success:
# Update the docker image in the Dockerhub repository
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#  - docker build -t $DOCKER_CI_REPO_NAME:latest .
#  - docker tag $DOCKER_CI_REPO_NAME:latest $DOCKER_CI_REPO_NAME:$IMAGE_TAG
#  - docker push $DOCKER_CI_REPO_NAME:latest
#  - docker push $DOCKER_CI_REPO_NAME:$IMAGE_TAG

matrix:
  include:
    # add deploy stage for dev
    - env: DEPLOY=dev
      if: branch = master
      deploy:
        provider: script
        # We need to set variables that are comming from travis ci setting
        # Variables:
          # - DOCKER_CI_REPO_NAME
          # - AWS_PROFILE_DEV
          # - AWS_ACCOUNT_USER_ID_DEV
          # - AWS_ACCOUNT_SECRET_DEV
          # - AWS_DEFAULT_REGION
        script: TRAVIS_PROFILE=$AWS_PROFILE_DEV TRAVIS_AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEV TRAVIS_AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEV TRAVIS_AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION ./deploy.sh -d && AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEV AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEV aws cloudfront create-invalidation --distribution-id E110AWTWK0G3RN --paths '/*'
        on:
          branch: master
    
    # Add deploy stage for PROD
    - env: DEPLOY=prod
      if: tag IS present
      deploy:
        provider: script
        script: TRAVIS_PROFILE=$AWS_PROFILE_PROD TRAVIS_AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_PROD TRAVIS_AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_PROD TRAVIS_AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION ./deploy.sh -p && AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_PROD AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_PROD aws cloudfront create-invalidation --distribution-id E3T6U9HGEXURZ9 --paths '/*'
        on:
          branch: master
          tags: true
