sudo: required

language: node_js
node_js:
  - node

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -o $HOME/.local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest && chmod +x $HOME/.local/bin/ecs-cli
  - aws configure set profile.lmb-dev.aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set profile.lmb-dev.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set profile.lmb-dev.region ap-southeast-1

cache:
  directories:
    - node_modules

before_script:
  - meteor npm install

script:
  - npm t
  - meteor build $HOME
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then aws s3 cp --acl public-read $HOME/frontend.tar.gz s3://unee-t-media/frontend/commit/${COMMIT}.tar.gz; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then aws s3 cp --acl public-read $HOME/frontend.tar.gz s3://unee-t-media/frontend/${TRAVIS_BRANCH}.tar.gz; fi'

deploy:
  provider: script
  script: bash deploy.sh $COMMIT
  skip_cleanup: true
  on:
      all_branches: true

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
