#Variable for this script are set in:
    # - Travis CI:
    #     - DOCKER_CI_REPO_NAME
    #     - AWS_DEFAULT_REGION
    # - AWS Parameter Store:
    #     - ROOT_URL
    #     - BUGZILLA_URL
    #     - BUGZILLA_ADMIN_KEY
    #     - MONGO_MASTER_USERNAME
    #     - MONGO_MASTER_PASSWORD
    #     - MONGO_CONNECT
    #     - CLOUDINARY_URL
    #     - CLOUDINARY_PRESET
    #     - API_ACCESS_TOKEN
    #     - FROM_EMAIL
    #     - MAIL_URL
    #     - INVITE_LAMBDA_URL
    #     - APIENROLL_LAMBDA_URL
    #     - UNIT_CREATE_LAMBDA_URL
    #     - PDFGEN_LAMBDA_URL
    #     - PDFCONVERT_LAMBDA_URL
    #     - STAGE
    #     - DOMAIN

version: '2'
services:
    meteor:
        image: $(DOCKER_CI_REPO_NAME):latest     
        mem_reservation: 1g
        mem_limit: 2g
        ports:
            - "8080:3000"
        environment:
            - ROOT_URL=${ROOT_URL}
            - BUGZILLA_URL=${BUGZILLA_URL}
            - BUGZILLA_ADMIN_KEY=${BUGZILLA_ADMIN_KEY}
            - MONGO_URL=mongodb+srv://${MONGO_MASTER_USERNAME}:${MONGO_MASTER_PASSWORD}@${MONGO_CONNECT}
            - CLOUDINARY_URL=${CLOUDINARY_URL}
            - CLOUDINARY_PRESET=${CLOUDINARY_PRESET}
            - API_ACCESS_TOKEN=${API_ACCESS_TOKEN}
            - FROM_EMAIL=${FROM_EMAIL}
            - MAIL_URL=${MAIL_URL}
            - INVITE_LAMBDA_URL=${INVITE_LAMBDA_URL}
            - APIENROLL_LAMBDA_URL=${APIENROLL_LAMBDA_URL}
            - UNIT_CREATE_LAMBDA_URL=${UNIT_CREATE_LAMBDA_URL}
            - PDFGEN_LAMBDA_URL=${PDFGEN_LAMBDA_URL}
            - PDFCONVERT_LAMBDA_URL=${PDFCONVERT_LAMBDA_URL}
            - STAGE=${STAGE}
            - DOMAIN=${DOMAIN}
        logging:
            driver: awslogs
            options:
                awslogs-region: $(AWS_DEFAULT_REGION)      
                awslogs-group: meteor            
                awslogs-stream-prefix: ecs
